# action.yml
name: 'Set Concourse Pipeline'
author: Playmint
description: 'Configures a concourse pipeline'
branding:
  icon: plus-circle
  color: green
inputs:
  url:
    description: 'The base concourse URL'
    required: true
  team:
    description: 'The concourse team where the pipeline lives'
    required: true
    default: 'main'
  pipeline:
    description: 'The concourse pipeline where the job lives'
    required: true
  vars:
    description: 'JSON blob of pipeline variables'
    required: false
  vars_files:
    description: 'JSON blob of paths to YAML files containing pipeline variables'
    required: false
  concourse-username:
    description: 'A local auth user with the rights to trigger the job'
    required: true
  concourse-password:
    description: 'The password for concourse-user'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CONCOURSE_URL: ${{ inputs.concourse-url }}
    CONCOURSE_USERNAME: ${{ inputs.concourse-username }}
    CONCOURSE_PASSWORD: ${{ inputs.concourse-password }}
    CONCOURSE_TEAM: ${{ inputs.concourse-team }}
  args:
  - pipelines
