
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to check the action works
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: repo
    - name: set_pipeline
      uses: playmint/github-action-set-pipeline@v1
      with:
        url: ${{ secrets.CONCOURSE_URL }}
        username: ${{ secrets.CONCOURSE_USERNAME }}
        password: ${{ secrets.CONCOURSE_PASSWORD }}
        team: main
        pipeline-name: action-example
        pipeline-config: repo/example/pipeline-config.yml
        pipeline-vars: repo/example/pipeline-vars.yml
        pipeline-paused: 'false'
